spring:
  application:
    name: HystrixDemo

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream # enable stream at http://localhost:8080/actuator/hystrix.stream